describe("ingredient info modal", () => {
    it("should be modal window open when clicking on an ingredient", () => {
        cy.contains("Сыр с астероидной плесенью")
            .click()
        cy.get("[class^=modal_content]")
            .find("p")
            .first()
            .should("have.text", "Детали ингредиента");
    })
    it("should be correctly displayed ingredient details", () => {
        cy.get("[class^=modal_content]")
            .find("p").should("have.length", "9").then( listOfAdds => {
            cy.wrap(listOfAdds)
                .eq(1)
                .should("have.text", 'Калории,ккал')
            cy.wrap(listOfAdds)
                .eq(2)
                .should("have.text", '3377')
            cy.wrap(listOfAdds)
                .eq(3)
                .should("have.text", 'Белки, г')
            cy.wrap(listOfAdds)
                .eq(4)
                .should("have.text", '84')
            cy.wrap(listOfAdds)
                .eq(5)
                .should("have.text", 'Жиры, г')
            cy.wrap(listOfAdds)
                .eq(6)
                .should("have.text", '48')
            cy.wrap(listOfAdds)
                .eq(7)
                .should("have.text", 'Углеводы, г')
            cy.wrap(listOfAdds)
                .eq(8)
                .should("have.text", '420')
        })
    })
    it("should be close modal window", () => {
        cy.get("[class^=modal_content]")
            .find("span")
            .click()
            .should("not.exist");
    })
})